services:
  nestjs-app:
    container_name: nestjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./dist:/app/dist
    environment:
      NODE_ENV: production
